version: "3.9"

services:
  redis:
    image: redis:alpine
    container_name:
      redis_db
    restart: always
    networks:
      - hotel_reservation_network
    ports:
      - '43321:6379'
    volumes:
      - cache:/data
    command: [ "redis-server", "--appendonly", "yes" ]

volumes:
  cache:

networks:
  hotel_reservation_network:
    external: true
