version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3.13-rc-management
    container_name: rabbitmq
    networks:
      - hotel_reservation_network
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    restart: always

networks:
  hotel_reservation_network:
    external: true
