version: "3.9"

services:
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: reservation_app
        networks:
            - hotel_reservation_network
            - reservation_service_network
        depends_on:
            - db

    nginx:
        image: nginx
        ports:
            - '${FORWARD_APP_PORT:-80}:80'
            - '${FORWARD_SSL_APP_PORT:-443}:443'
        volumes:
            - ./:/home/php-app/application
            - ./docker/nginx/config.conf:/etc/nginx/conf.d/default.conf
        networks:
            - reservation_service_network
        depends_on:
            - php
            - db

    db:
        image: mysql:8.1
        container_name: reservation_service_db
        command:
            - --general-log=1
            - --max_allowed_packet=512M
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            TZ: UTC
        networks:
            - reservation_service_network
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'

    db_test:
        image: mysql:8.1
        container_name: reservation_service_db_test
        command:
            - --general-log=1
        environment:
            MYSQL_DATABASE: reservation_service_test
            MYSQL_ROOT_PASSWORD: root
            TZ: UTC
        networks:
            -   reservation_service_network
        ports:
            - '${FORWARD_DATABASE_TEST_PORT:-3306}:3306'

networks:
    reservation_service_network:
        driver: bridge
    hotel_reservation_network:
        external: true
