version: "3.9"

services:
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: app_example
        networks:
            - hotel_reservation_network
            - example-app-network
        depends_on:
            - db

    nginx:
        image: nginx
        ports:
            - '${FORWARD_APP_PORT:-80}:80'
            - '${FORWARD_SSL_APP_PORT:-443}:443'
        volumes:
            - ./:/home/php-app/application
            - ./docker/nginx/config.conf:/etc/nginx/conf.d/default.conf
        networks:
            - example-app-network
        depends_on:
            - php
            - db

    db:
        image: mysql:8.1
        container_name: db_example
        command:
            - --general-log=1
            - --max_allowed_packet=512M
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            TZ: UTC
        networks:
            - example-app-network
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'

    db_test:
        image: mysql:8.1
        container_name: db_test_example
        command:
            - --general-log=1
        environment:
            MYSQL_DATABASE: test_db
            MYSQL_ROOT_PASSWORD: root
            TZ: UTC
        ports:
            - '${FORWARD_DATABASE_TEST_PORT:-3306}:3306'

networks:
    example-app-network:
        driver: bridge
    hotel_reservation_network:
        external: true
